### ISSUE TITLE
README.rst doesn't render on PyPI

### ISSUE THREAD

**Issue by chrissimpkins** [thomasleese/mo#2]
This project looks fantastic Thomas.  I'm a huge YAML fan and love this idea.  

Just a quick note to let you know that your README.rst file is not rendering on PyPI.  Seems like valid rst here in the repo.  Not sure where the problem lies.

**Comment by thomasleese** [comment]
Thanks for the heads up!

I've committed 83372a06e0db2e47480a9a3f7cc963e9f189a311 which I think might fix the issue, but I can't test it until I make a new release (I think!), so I'll leave this issue open for the time being.

**Comment by chrissimpkins** [comment]
You can directly edit your rst files (and other project metadata) in PyPI. Use the edit button next to the current release:

<img width="649" alt="edit" src="https://cloud.githubusercontent.com/assets/4249591/13113597/b7ef2c12-d55d-11e5-85dd-33bbc64ac19e.png">

The copy/paste your current repo version.  :+1:

**Comment by chrissimpkins** [comment]
By the way, it is not intuitive terminology but you have to click the `Add Information` button at the bottom of the screen to save it...

**Comment by thomasleese** [comment]
Oh, awesome, thanks! It's looking a little better now, need to make the image a bit smaller.

**Comment by chrissimpkins** [comment]
Great! Look forward to giving this a try.  Will close the issue.
